package com.qualogo.chatserver.models;

import jakarta.persistence.*;

/**
 * The Role class represents a role entity in the system.
 * It is mapped to the "roles" table in the database.
 */
@Entity
@Table(name = "roles")
public class Role {
  
  /**
   * The unique identifier for the role.
   * It is auto-generated by the database.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Integer id;

  /**
   * The name of the role.
   * It is stored as a string in the database with a maximum length of 20 characters.
   */
  @Enumerated(EnumType.STRING)
  @Column(length = 20)
  private ERole name;

  /**
   * Default constructor for the Role class.
   */
  public Role() {

  }

  /**
   * Constructor for the Role class that initializes the role with a specific name.
   * 
   * @param name the name of the role
   */
  public Role(ERole name) {
    this.name = name;
  }

  /**
   * Gets the unique identifier of the role.
   * 
   * @return the id of the role
   */
  public Integer getId() {
    return id;
  }

  /**
   * Sets the unique identifier of the role.
   * 
   * @param id the id to set
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * Gets the name of the role.
   * 
   * @return the name of the role
   */
  public ERole getName() {
    return name;
  }

  /**
   * Sets the name of the role.
   * 
   * @param name the name to set
   */
  public void setName(ERole name) {
    this.name = name;
  }
}